### ISSUE TITLE
Logo shows two colors for notification 

### ISSUE THREAD

**Issue by AeliusSaionji** [CurtisMJ/LogoPlus#12]
If I pick orange for an app, then the logo will flash yellow then red! Maybe there's a timing issue? The colors I see are always related to the chosen color, and some colors do work. The service doesn't seem to be correctly generating most colors.

**Comment by CurtisMJ** [comment]
There are edge cases where colors would turn out a bit wrong. This is mostly due to the ticks on the controller not quite lining up (The instructions add specific numbers to the registers per tick and you can only specify the number of times it does it). I had a solution at some point but the resulting microcode was very large. The tradeoff  for the larger controller program was less colors on the logo at once. Perhaps giving  the option of sacrificing  controller memory use for higher quality colors is a good idea.

**Comment by AeliusSaionji** [comment]
Yeah- given that I am seeing 2 colors per app, I am having some trouble identifying what app is supposed to be generating the color I'm seeing. I would like to have what I see reflect the setting I choose. Having "all the colors" means little if the colors are not working :)

**Comment by AeliusSaionji** [comment]
Or at the very least: have the color picker activate the logo light in the same way the service will. Then I can play with the color picker and quickly see how the light will respond to a selection.

**Comment by CurtisMJ** [comment]
Color picker now previews notification colors
Additionally changes to microcode generation were rolled back which should resolve timing issues.
Please open a new issue if the colors are still wonky.

**Comment by AeliusSaionji** [comment]
Thanks for the update! It's much better now, although there are still minor timing issues for certain colors (orange in particular).

Only used this version for about a day though. I installed the Razer update that just released and unfortunately I am currently awaiting Arter to release a new kernel before I can root again.
